# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('ffd3bf34bec27f4d2279ec2bf9eb2604_MzA4MzgyMjAxMy0xMi0wMyAxMDozNzo0NS41NTMxMDY')
  end)
end
